# Generated by Django 4.1.7 on 2023-08-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register23', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_records',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
