# Generated by Django 4.1.7 on 2023-08-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register23', '0002_member_records_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_records',
            name='code_hash',
            field=models.CharField(max_length=190, null=True),
        ),
    ]
