# Generated by Django 4.1.7 on 2023-08-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register23', '0003_alter_member_records_code_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_records',
            name='email',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='member_records',
            name='p_number',
            field=models.CharField(max_length=190, null=True),
        ),
    ]
