# Generated by Django 4.1.7 on 2023-08-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register23', '0004_member_records_email_member_records_p_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_records',
            name='date_created',
            field=models.CharField(max_length=190, null=True),
        ),
    ]
