# Generated by Django 4.1.7 on 2023-09-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register23', '0005_alter_member_records_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_records',
            name='date_b',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='member_records',
            name='u_major',
            field=models.CharField(max_length=190, null=True),
        ),
    ]
